/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getNumCpus(): number

export declare function greet(name: string): string

export declare function plus100(input: number): number

export declare function printArray(arr: Uint8Array): void
